### ISSUE TITLE
Custom Updater changed to HACS (Home Assistant Community Store)

### ISSUE THREAD

**Issue by Ernst79** [gurbyz/power-wheel-card#22]
Custom Updater for Home Assistant has stopped and moved to a new update tool for custom components, which is called HACS. See here for more info. 

https://custom-components.github.io/hacs/

Is it possible to update power-wheel-card in a way that it can be added in HACS. Instructions for preparing your component are also on the above mentioned website.

**Comment by filoor** [comment]
i'm also looking for a HACS intergration

**Comment by gurbyz** [comment]
I'll have a look into HACS soon and migrate from Custom_updater to HACS.

**Comment by gurbyz** [comment]
First I had to take some time to migrate my own HA instance from customer_updater to HACS. That's working now.

Now I'm facing some [requirements of HACS](https://custom-components.github.io/hacs/developer/plugin/) that the power-wheel-card repo doesn't comply to. It basically means I have to abandon my current repo. I'm not happy with that. Hopefully HACS is able to use multi card repo's soon or that I'll find an alternative solution. This will take some time.

**Comment by gurbyz** [comment]
I've started [preparations](https://github.com/gurbyz/custom-cards-lovelace/commit/acfdc75ff60b76ea3cde9ede5b4f616319dfef54) for HACS support on `dev` branch. I had to do changes to the repository structure. I will do the rename of the repo later and have to see what else is needed for HACS.

**Comment by gurbyz** [comment]
The repo (v0.0.15) is prepared for HACS now. But HACS has to accept the card first before you can find it as a plugin in the HACS UI.

**Comment by ViperRNMC** [comment]
Hi gurbyz, thanks for the update, i manualy add the plugin to hacs and it works

**Comment by gurbyz** [comment]
PR for HACS repo can be followed here: https://github.com/custom-components/hacs/pull/479

**Comment by gurbyz** [comment]
PR for HACS is merged and `power-wheel-card` is available in the store.
