### ISSUE TITLE
Card no longer rendering on HA 106

### ISSUE THREAD

**Issue by PaulAntonDeen** [gurbyz/power-wheel-card#36]
I have read the wiki about what to try first before creating a bug report.

**Which custom card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
0.106

**Which version of the card do you use?**
0.0.16 (from HACS)

**Describe the bug**
A clear and concise description of what the bug is. Paste any error messages.
![image](https://user-images.githubusercontent.com/25848961/75523788-fbdea000-5a0c-11ea-873b-78b2c7a1e7e8.png)

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
auto_toggle_view_period: 10
color_icons: true
consuming_color: 'var(--label-badge-yellow, #f4b400)'
debug: false
energy_decimals: 3
grid_power_consumption_entity: sensor.power_consumption
grid_power_production_entity: sensor.power_production
initial_auto_toggle_view: false
initial_view: power
money_decimals: 2
money_unit: €
power_decimals: 3
producing_color: 'var(--label-badge-green, #0da035)'
production_is_positive: 1
solar_power_entity: sensor.solar_now_kw
title: Power wheel
title_energy: Power wheel
title_money: Power wheel
title_power: Power wheel
type: 'custom:power-wheel-card'
```

**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.
![image](https://user-images.githubusercontent.com/25848961/75524265-dc944280-5a0d-11ea-82ca-758faae92688.png)

Example: power-wheel-cardVersion: 0.0.10Lovelace resource: power-wheel-card.js?v=0.0.10HA version: 0.87.1Report issues here: ...etc...

**Expected behavior**
Normal powerwheel behavior as on 0.105 and lower

**Screenshots**
If applicable, add screenshots to help explain your problem. see error

**Additional context**

**Comment by cyberjunky** [comment]
Yes same here on  0.106.1
```
can't define property "production_is_positive": Object is not extensible

type: 'custom:power-wheel-card'
grid_power_consumption_entity: sensor.stroom_verbruik
grid_power_production_entity: sensor.stroom_levering
solar_power_entity: sensor.omnik_sensor_power_generation
id: power_wheel
title: Energieverbruik
color_icons: true
view: power
```

**Comment by gurbyz** [comment]
Duplicate of #35.

**Comment by PaulAntonDeen** [comment]
Reinstall did not fix it by itself. However upgrading the ?v= to the next number did help.

**Comment by gurbyz** [comment]
> Reinstall did not fix it by itself. However upgrading the ?v= to the next number did help.

Thanks for putting this workaround here. 

You were impacted by a caching issue. That can also be solved by refreshing your browser once while bypassing your service workers for network (and disable it again after refreshing). 
![image](https://user-images.githubusercontent.com/3920372/75546848-ceecb600-5a29-11ea-8d18-ec25fc79ff1d.png)
