### ISSUE TITLE
3 decimals on Power

### ISSUE THREAD

**Issue by bluemantwo** [gurbyz/power-wheel-card#39]
I have read the wiki about what to try first before creating a bug report.

**Which custom card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
0.107.5

**Which version of the card do you use?**
0.0.16

**Describe the bug**
Energy display shows 3 decimals for Whr even when energy_decimals is set to 0.  If set to 1, it correctly shows 1.  Same with 2, 3,4,5, etc.  But no way to get 0 decimals.  

Power display works fine with 0 decimals.   

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
type: 'custom:power-wheel-card'
title_power: Solar Power
title_energy: Solar Energy Today
grid_power_entity: sensor.power_now_meter_w
home_power_entity: sensor.power_now_usage_w
solar_power_entity: sensor.power_now_solar_w
solar_energy_entity: sensor.power_produced_today
grid_energy_consumption_entity: sensor.power_imported_today
grid_energy_production_entity: sensor.power_exported_today
initial_auto_toggle_view: false
power_decimals: 0
energy_decimals: 0
production_is_positive: false
```

**Screenshots**

![Capture](https://user-images.githubusercontent.com/22325437/77254312-820d9100-6c1d-11ea-8fdb-5011261b55c5.JPG)

**Comment by gurbyz** [comment]
f77a30a0229cf4aae3400c6f98197d3c0281d7b8

**Comment by gurbyz** [comment]
Thank you for reporting the issue. It should be fixed now. Version 0.1.0 is released.
