### ISSUE TITLE
Using home power sensor (feature request)

### ISSUE THREAD

**Issue by Tonno87** [gurbyz/power-wheel-card#45]
Hi! 
I want to use your power-wheel-card, but my installation is incompatible. 
I need to use the value of my home power sensor for calculating the powerwheel. 

![image](https://user-images.githubusercontent.com/59800400/79630386-21f10880-8151-11ea-947c-17d3586712dc.png)

On this picture the value 252W is my home power sensor. Is it possible to add it as an optional feature like grid_power_entity (C)? Otherwise i can only use Energy card..

Best regards.
Dennis

**Comment by gurbyz** [comment]
I understand you don't have a sensor that's measuring the power that's imported/exported to the grid. And for the moment you use "a home power sensor" as a workaround to make the card work, but of course you don't have correct values in the power view of the card.

Maybe you can make a sensor yourself in home assistant? That's called a 'template sensor' and its value is based on values of other sensor(s). There an example (not suitable for you, but as example what a template sensor can do) [here](https://github.com/gurbyz/power-wheel-card#Example-requirements-configuration) in the readme file.

**Comment by Tonno87** [comment]
Okay, this workaround works well:
![image](https://user-images.githubusercontent.com/59800400/79644488-a1aac180-81a9-11ea-8594-d2759a1fa979.png)

Code:
`        value_template: >-
          {{ ((states('sensor.modbus_sma_pv_power') | float) - (states('sensor.pulse_width_sensor') | float))}}`

My problem is fixed, thanks!

**Comment by gurbyz** [comment]
Super!
