### ISSUE TITLE
Displaying NaN while no produced power (solar_power_entity is unknown).

### ISSUE THREAD

**Issue by lrybak** [gurbyz/power-wheel-card#47]
I have read the wiki about what to try first before creating a bug report.

**Which version of HA do you use?**
0.109.2

**Which version of the card do you use?**
v0.1.0

**Describe the bug**
Displaying NaN while no produced power (solar_power_entity is unknown).
![nan](https://user-images.githubusercontent.com/5631648/80846640-316e5800-8c0d-11ea-9156-2e34bcb3ea45.png)

**Configuration of the card**
```
  - type: "custom:power-wheel-card"
	title_power: Power
	title_energy: Daily energy
	solar_icon: mdi:white-balance-sunny
	production_is_positive: true
	home_icon: mdi:home-assistant
	solar_power_entity: sensor.fronius_ac_power
	solar_energy_entity: sensor.fronius_day_energy
	grid_energy_consumption_entity: sensor.grid_energy_consumption_daily
	grid_energy_production_entity: sensor.grid_energy_production_daily
	grid_power_consumption_entity: sensor.grid_power_consumption
	grid_power_production_entity: sensor.grid_power_production
```
**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.
```
Version: 0.1.0
Lovelace resource: power-wheel-card.js
HA version: 0.109.2
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Report issues here: https://github.com/gurbyz/power-wheel-card/issues
Processed config: {
 "type": "custom:power-wheel-card",
 "title_power": "Power",
 "title_energy": "Daily energy",
 "solar_icon": "mdi:white-balance-sunny",
 "production_is_positive": 1,
 "home_icon": "mdi:home-assistant",
 "debug": true,
 "solar_power_entity": "sensor.fronius_ac_power",
 "solar_energy_entity": "sensor.fronius_day_energy",
 "grid_energy_consumption_entity": "sensor.grid_energy_consumption_daily",
 "grid_energy_production_entity": "sensor.grid_energy_production_daily",
 "grid_power_consumption_entity": "sensor.grid_power_consumption",
 "grid_power_production_entity": "sensor.grid_power_production",
 "title": "Power wheel",
 "title_money": "Power wheel",
 "power_decimals": 0,
 "energy_decimals": 3,
 "money_decimals": 2,
 "money_unit": "€",
 "color_icons": true,
 "consuming_color": "var(--label-badge-yellow, #f4b400)",
 "producing_color": "var(--label-badge-green, #0da035)",
 "initial_view": "power",
 "initial_auto_toggle_view": false,
 "auto_toggle_view_period": 10
}
Registered sensors: [
 "sensor.fronius_ac_power",
 "sensor.grid_power_consumption",
 "sensor.grid_power_production",
 "sensor.fronius_day_energy",
 "sensor.grid_energy_consumption_daily",
 "sensor.grid_energy_production_daily"
]
Views object: {
 "power": {
  "title": "Power",
  "oneGridSensor": false,
  "twoGridSensors": true,
  "batteryCapable": false,
  "capable": true,
  "unit": "W"
 },
 "energy": {
  "title": "Daily energy",
  "oneGridSensor": false,
  "twoGridSensors": true,
  "capable": true,
  "unit": "kWh"
 },
 "money": {
  "title": "Power wheel",
  "oneGridSensor": false,
  "twoGridSensors": true,
  "capable": false,
  "unit": "€"
 }
}
```

**Expected behavior**
Can you handle unknown input value as 0 (zero)?

**Screenshots**
![nan](https://user-images.githubusercontent.com/5631648/80846650-3c28ed00-8c0d-11ea-867e-a63cd0c4d007.png)
![fronius](https://user-images.githubusercontent.com/5631648/80846655-41863780-8c0d-11ea-9bce-c0fdfc4760a6.jpg)
![templates_values](https://user-images.githubusercontent.com/5631648/80846658-43e89180-8c0d-11ea-97f5-7d2758886fec.png)

**Comment by gurbyz** [comment]
Hi, there is a work around for this [here](https://community.home-assistant.io/t/lovelace-power-wheel-card/82374/81?u=gurbyz) on the forum. Maybe the work around fits for you too?

If will have a look later if I can implement your feature request in an easy way. I'll leave this issue open for now.

**Comment by lrybak** [comment]
Hello, Thanks for your feedback. The workaround you mentioned is for sure the easiest way to fix this particular issue. I will go for it. From he other hand I think it would be good, if it's easly doable, to implement such condition to treat undefined as zero in your code.
BTW. Many thanks for very usefull card. Appreciate your work!
