### ISSUE TITLE
HA Icons in 0.110 beta

### ISSUE THREAD

**Issue by VDRainer** [gurbyz/power-wheel-card#48]
I have read the wiki about what to try first before creating a bug report.

**Which version of HA do you use?**
0.110.0b0
**Which version of the card do you use?**
latest
**Describe the bug**
From a note to another custom-card developer

> In Home Assistant 0.110 the way icons are loaded is changed. This means the paper-icon-button that is used in this element will no longer show the correct icon. You can use ha-icon-button that uses mwc-icon-button underneath as a replacement.

The Icons are to small after 0.110 beta
![Auswahl_330](https://user-images.githubusercontent.com/26381449/82043033-2e627580-96ab-11ea-9e28-09622b67b3ca.png)

**Comment by gurbyz** [comment]
Thx for reporting this on power-wheel-card, probably v0.1.0. I can't find much information on this change beside this [dev blog post](https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets). The card is using `ha-icon` by the way. I will update to 0.110.0b2 and have a look.

**Comment by VDRainer** [comment]
There's a note about icon size on discoed beta channel.
https://discord.com/channels/330944238910963714/427516175237382144/710812179313459295
Maybe of use.
Thanks for looking!

**Comment by gurbyz** [comment]
I made a preliminary fix for the icon sizes. It's on dev branch now as version 0.1.1b-dev. Have to release it in the next couple of days. But maybe I can find a better fix later.

**Comment by VDRainer** [comment]
Thanks @gurbyz !
Waited for a few other custom-card fixes, but now i'm on 0.110.0b3.
Your fix works for me.
Does this dev version also include the `invert_grid_color` flag? :smile:

**Comment by gurbyz** [comment]
Thx for testing. Yes, the flag will also be there. :-D Please note the extra `s` in `invert_grid_colors` I added for the card.
