### ISSUE TITLE
Feature request - ability to set card title: none or false or null

### ISSUE THREAD

**Issue by peterhoe** [gurbyz/power-wheel-card#51]
I have read the wiki about what to try first before creating a bug report.

**Which version of HA do you use? **
- HaasV111.0

**Which version of the card do you use? **
0.1.1

**Describe the bug**
Feature request - ability to set title: none, or title: null or title: false
so that there is no title in the power wheel card, only displayed icons.
attempting to use any of the above values, shows default "Power Wheel" title

**Configuration of the card**
Copy the complete configuration of the card, even if you think it isn't relevant.
```
          - type: custom:power-wheel-card
            title: PV Batt Grid
            title_power: PV Batt Grid
            debug: false
            solar_icon: mdi:solar-power
            home_icon: mdi:home-city-outline
            solar_power_entity: sensor.modbus_sb_pv_production
            grid_power_consumption_entity: sensor.mqtt_sm_purchased_electricity
            grid_power_production_entity: sensor.mqtt_sm_grid_feed_in
            battery_power_entity: sensor.modbus_ss_supply_load_inverted
            battery_soc_entity: sensor.modbus_ss_charge_level
```

**Dev console debug output**
Add `debug: true` to your card parameters. Copy the complete output of the card that is logged to your dev console.
{ "type": "custom:power-wheel-card"
"title": "PV Batt Grid"
"title_power": "PV Batt Grid"
"debug": true
"solar_icon": "mdi:solar-power"
"home_icon": "mdi:home-city-outline"
"solar_power_entity": "sensor.modbus_sb_pv_production"
"grid_power_consumption_entity": "sensor.mqtt_sm_purchased_electricity"
"grid_power_production_entity": "sensor.mqtt_sm_grid_feed_in"
"battery_power_entity": "sensor.modbus_ss_supply_load_inverted"
"battery_soc_entity": "sensor.modbus_ss_charge_level"
"production_is_positive": 1
"title_energy": "PV Batt Grid"
"title_money": "PV Batt Grid"
"power_decimals": 0
"energy_decimals": 3
"money_decimals": 2
"money_unit": "€"
"color_icons": true
"consuming_color": "var(--label-badge-yellow, #f4b400)"
"producing_color": "var(--label-badge-green, #0da035)"
"invert_grid_colors": false
"active_arrow_color": "var(--paper-item-icon-active-color, #fdd835)"
"initial_view": "power"
"initial_auto_toggle_view": false
"auto_toggle_view_period": 10}Registered sensors: [ "sensor.modbus_sb_pv_production"
"sensor.mqtt_sm_purchased_electricity"
"sensor.mqtt_sm_grid_feed_in"
"sensor.modbus_ss_supply_load_inverted"
"sensor.modbus_ss_charge_level"]Views object: { "power": {  "title": "PV Batt Grid"
 "oneGridSensor": false
 "twoGridSensors": true
 "batteryCapable": true
 "capable": true
 "unit": "w" }
 "energy": {  "title": "PV Batt Grid"
 "oneGridSensor": false
 "twoGridSensors": false
 "capable": false }
 "money": {  "title": "PV Batt Grid"
 "oneGridSensor": false
 "twoGridSensors": false
 "capable": false
 "unit": "€" }}

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gurbyz** [comment]
Good feature request. I tried to find a workaround in e.g. ```title: ' '``` but that does something strange for the positioning of the solar icon.

**Comment by clsgroen** [comment]
+1

**Comment by coen17st** [comment]
+1

**Comment by gurbyz** [comment]
You can omit the `title` parameter now.
