### ISSUE TITLE
Mapping of sensors

### ISSUE THREAD

**Issue by Tokn59** [gurbyz/power-wheel-card#60]
Hi, thanks for sharing this great integration !

I have some difficulties mapping the right sensors.

I have the following sensors through DSMR (working om modbus integration)

sensor.energydel -> This is the TOTAL Kwh consumed
sensor.energyret -> This is the TOTAL Kwh produced
sensor.powerdel -> The current power delivery
sensor.powerret -> The current power produced
sensor.powerretl1 -> Same as powerret ???

If more energy is produced than consumed powerdel = 0
If more energy is consumed than produced powerret = 0

My DSMR values are :

![dsmr](https://user-images.githubusercontent.com/9215231/94438729-cd41c700-019f-11eb-9bab-dc01a1c49b2e.jpg)

For now I did the following : 

![power card](https://user-images.githubusercontent.com/9215231/94438812-e77ba500-019f-11eb-9182-d52a97d94159.jpg)

How would you map this in the card ?

Also I have delivery and return seperate for day/night so actually 4 values.

Many thanks & KInd regards,

Tony

**Comment by Tokn59** [comment]
New update .. Got it to work just fine but I get the error "Units not equal for all sensors for the power view". All values are in Kwh ... This is the card configuration. Any ideas ?

![power wheel issue](https://user-images.githubusercontent.com/9215231/94688989-9817af00-032e-11eb-8439-1bc9a41cbf2b.jpg)

**Comment by gurbyz** [comment]
The card looks for this unit information in the sensors itself. You can check in Home Assistant > Developer Tools > States if the `unit_of_measurement` is present and correct in all your sensors. Please note that `Kwh` (as you write in your second command) isn't the same as `kWh`. The casing (upper or lower) should also resemble.

If some of your sensors lack the unit information, you could add it yourself in Home Assistent. If you didn't make the sensors yourself, you can still add the unit like [here](https://www.home-assistant.io/docs/configuration/customizing-devices).

**Comment by gurbyz** [comment]
Looking at your config in your second comment: you shouldn't use the same sensor for `solar_power_entity` as for `grid_power_production_entity`. That can't be correct.

`solar_power_entity` should be used with a sensor that measures your solar panels (=your power inverter).

If you have troubles understanding the readme file, please use the [readme file on dev branch](https://github.com/gurbyz/power-wheel-card/blob/dev/README.md). That one is already rewritten and more to the point.

**Comment by ppumkin** [comment]
Hello - (sorry to hijack this but it seems related) I seem to be misunderstanding something too. 

You can see that 
- PV 614W 
- load 609W (how much my house is using)
- grid usage 0 (so no import and no export)

On the power wheel it is showing
 - bottom left power line icon (grid?? should be 0 but its 609)
   - why is this not under my home icon?
- The value under the home icon (bottom right) is 1223W ??

![image](https://user-images.githubusercontent.com/1249683/94915295-88ba7200-04a4-11eb-8998-32f55510ca81.png)
![image](https://user-images.githubusercontent.com/1249683/94915317-966ff780-04a4-11eb-9ca2-0cc96d44d807.png)

**Comment by ppumkin** [comment]
Obviously after I wrote the above I played around a bit and realised what the problem was.
I was plugging in too much data- I really love your plugin thanks a lot.. but the documentation is still a bit confusing.

![image](https://user-images.githubusercontent.com/1249683/94916366-77726500-04a6-11eb-9f8b-32f9de0b79f1.png)

![image](https://user-images.githubusercontent.com/1249683/94916383-7e997300-04a6-11eb-871c-f0f2a704edd0.png)

**Comment by Tokn59** [comment]
My extra problem is the data comes from 2 different devices. Solar production comes directly from the Sunnyboy via modbus integration whilst my power consumption (momentaneous) comes from a DIY device connected to smart metering.

In developer tools I see : 

Device 1:
sensor.powerret unit of measurement : W (current value 0.548)   (unit of measurement does not seem right as it is indeed 548 W and so 0.548 kW)

Device 2: 
sensor.smapwrl1 unit of measurement : kW (current value 0.84)

Secondary problem :  Night and Day consumption and production are different meters (On Device 1)

Any hints are more than welcome !

**Comment by ppumkin** [comment]
@Tokn59  I am new to HomeAssistant but maybe its worth trying to see if you can create two new  sensors, that take values from your other sensors based on your criteria.. I'm not sure.. is that going to be a Script maybe? An automation? 

So I thought my problem was solved with using PV input and Grid.. but the values are still very strange.
Why does it look like my house is exporting electricity with PV? 
Is it not supposed to be the PV arrow green to my house, and the GRID ---> shows import?

![image](https://user-images.githubusercontent.com/1249683/94943114-22971480-04cf-11eb-9a63-855c726614ca.png)

**Comment by gurbyz** [comment]
> maybe instead of writing "either A or B+C" be more explicit. "When using B+C do not use A"

That's a good one. I'll add something to the docs.

What these B+C sensors are for: some people have B+C sensors (instead of the usual A sensor). When your A sensor would turn negative, their B becomes 0 and their C gets the absolute value of your A sensor. But please forget, it's very rare.

**Comment by gurbyz** [comment]
> Device 1:
> sensor.powerret unit of measurement : W (current value 0.548) (unit of measurement does not seem right as it is indeed 548 W and so 0.548 kW)

You can use a [template sensor](https://www.home-assistant.io/integrations/template/). I.e. you have to create one. This should help you start with it:

```
sensor:
  - platform: template
    sensors:
      my_better_sensor:
        friendly_name: 'My better sensor'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (1000 * (states("sensor.my_original_sensor") | float) | int }}
```

You can do similar things to get a total sensor for you day and night sensors.

```
value_template: >-
          {{ (states("sensor.my_original_day_sensor") | float) + (states("sensor.my_original_night_sensor") | float) }}
```

**Comment by gurbyz** [comment]
> I looks like I am exporting 3kw to the grid for some reason?

You have `grid_power_entity: sensor.inverter_grid`, so the value of this sensor is shown at the grid icon. Since `production_is_positive: true` the card will interpret the positive value 3035 as 'producing/exporting to the grid' and the grid icon will turn green according that.

I don't know for sure what your 'Inverter load' and 'Inverter grid' sensor measure, but if you expected a grid **import** (a.k.a. grid consumption) of 2880, you can try `production_is_positive: false`.

**Comment by Tokn59** [comment]
Done and working ! Thank You !!!

**Comment by ppumkin** [comment]
@gurbyz - I had a typo in the config

`production_is_postive: false`  -- missing i in the pos**i**tive bit

It works now 😄 

To answer your question
- LOAD - This is how much power my house is using in total. Like a central watt monitor for my whole house. 🥰 
- GRID - Measured at the meter for buying or selling
- - Positive means buying that much power (import)
- - 0 so no buying or selling of power, purely powered by solar
- - Negative means selling that much power (export)
