### ISSUE TITLE
Problem with directions of energy and values display

### ISSUE THREAD

**Issue by rgcouto** [gurbyz/power-wheel-card#67]
I have read the wiki about what to try first before creating a bug report.

**Which version of HA do you use?**
Version 247 | HassOS 4.13

**Which version of the card do you use?**
v0.1.4

**Describe the bug**
As visible in the screenshots, the solar panels (left bottom graph) are producing more than the house is consuming (left upper graph) but the power-wheel is not showing that information and is also showing an incorrect value of the actual house consumption.

**Configuration of the card**
```
type: 'custom:power-wheel-card'
title: Power wheel
solar_power_entity: sensor.shelly_em_produced_by_solar_panels
grid_power_entity: sensor.shelly_em_consumed_from_grid
debug: false
```

**Expected behavior**
When solar panels are producing more than the house consumes:
- the arrows should point from solar panel to house and grid
- the consumption value of the house should be the `PRODUCED_BY_SP - INJECTED_IN_GRID`

When solar panelas are not producing enough power than house consumes:
- the arrows should point from solar panel and grid to house
- the consumption values should also match

**Screenshots**
![image](https://user-images.githubusercontent.com/4560082/96099127-cf5b9380-0eca-11eb-942f-2b2ef467e345.png)

**Additional context**
I love the idea of this card, is actually more informative that any plot out there since I get a real idea of what's actually going on on my electrical consumptions. Keep up the great work! If you are coming anywhere near Coimbra (Portugal) someday, please mail me so that I can buy you coffee and some local delicious pastries! You deserve it!

**Comment by gurbyz** [comment]
Thanks for the amount of information in your issue. That helps finding the cause. I think the polarity of the grid_power_entity isn't what the card expects. It expects positive values for producing to the grid. In your upper left image, I see a negative value. You can switch the polarity by adding
```
production_is_positive: false
```
to your config.

Thanks for the invitation for coffee. Love the idea.

**Comment by rgcouto** [comment]
Yes, that was it! I'm pretty sure I've tried that and it didn't work at first, but now it's working which is what matters :) 

Thanks a lot for the help!
