### ISSUE TITLE
HACS install no card type found

### ISSUE THREAD

**Issue by tane64** [gurbyz/power-wheel-card#76]
Installed the Power wheel card via HACS

getting error No card type found

Resources looks good.
/hacsfiles/power-wheel-card/power-wheel-card.js  JavaScript Module

No card type configured
- type: 'custom:power-wheel-card'
  title: Power wheel
  solar_power_entity: sensor.shellyem_5e209e_channel_1_power_solar12
  grid_power_entity: sensor.p1_net_electricity_point
  debug: true

Hope you can help me.

**Comment by gurbyz** [comment]
What you describe sounds okay.

Did you press 'Reload resources' in the top right menu? And after that maybe a browser refresh and a 'Refresh' in the top right menu?

If that doesn't work, please check in your instance if the file is really there where you point to. `/hacsfiles/power-wheel-card/power-wheel-card.js` converts to `/www/community/power-wheel-card/power-wheel-card.js` on my instance of Home Assistant. (So in resources the url is different than were to expect the file. This is HACS related. Not my card related.)

If that doesn't help, you could try reinstalling the integration with HACS.

**Comment by tane64** [comment]
Hi,
> When i change the resource path to the suggested /www/community/power-wheel-card/power-wheel-card.js
  wil get aan error.


After reinstalling display problem is solved. but the wheel will stil not work.

Hacs auto install is done in
/Volumes/config/www/community/power-wheel-card

All the other components are installed in custom_components.






Manually copying the files to custom_components also dit not solve the problem.
Looks like a HACS probleem…Will do a full manual installation.


--

**Comment by gurbyz** [comment]
This HACS url thing is a little confusing isn't it? The resource url `/hacsfiles/power-wheel-card/power-wheel-card.js` differs from where the file actually can be found on your system (`/www/community/power-wheel-card/power-wheel-card.js` or maybe something else). If you see a folder `custom_components` on your system, could that be a folder from the pre-HACS era when everybody had to install their extra integrations manually? (In my case HACS itself is installed in this folder).

If you're trying the manual install, pls find some info about that here: https://github.com/gurbyz/power-wheel-card#manual-installation-advanced-users Especially useful when you want to upgrade to future versions of the card. Note that with manual install the resource path (`/local`) also differs from where you actually put the file on your system.

**Comment by tane64** [comment]
Probleem solved:
Remove, reinstall, remove browser cache.

**Comment by LustigePerson** [comment]
> Probleem solved: Remove, reinstall, remove browser cache.

So you got it to work via hacs? Because I am stuck with the same issue I guess.

**Comment by mariobrosch** [comment]
same issue here, install, other computer, same error as above:
![image](https://github.com/gurbyz/power-wheel-card/assets/9047518/7451e8e8-59d4-4178-b407-e888029e65b9)

even reinstall ctrl-r in browser does not help
